#!/bin/bash -e

if [ "$1" == "-no_inline" ]; then
    output_file_name=$(basename $2 .lat)
    # Uruchomienie latc z opcją "no_inline"
    if ./latc $1 $2 > $output_file_name.ll; then
        llvm-link -S $output_file_name.ll ./lib/runtime.bc | llvm-as -o $output_file_name.bc
    else
        rm -f $output_file_name.ll
        exit 1
    fi
else
    output_file_name=$(basename $1 .lat)
    if ./latc $1 > $output_file_name.ll; then
        llvm-link -S $output_file_name.ll ./lib/runtime.bc | llvm-as -o $output_file_name.bc
    else
        rm -f $output_file_name.ll
        exit 1
    fi
fi
